name: base CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
#      - uses: actions/setup-node@v6
#        with:
#          node-version-file: '.nvmrc'

#      - name: Install dependencies
#        run: npm ci
#
#      - name: Build
#        run: npm run build

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: trello-be:latest
