name: cache docker mount CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache mount
        uses: actions/cache@v4
        id: cache-mount
        with:
          path: cache-mount
          key: cache-mount-${{ hashFiles('package-lock.json') }}
          restore-keys: cache-mount-

      - name: Restore Docker cache mounts
        uses: reproducible-containers/buildkit-cache-dance@v3
        with:
          builder: ${{ steps.setup-buildx.outputs.name }}
          cache-map: |
            {
              "cache-mount": "/root/.npm"
            }

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: trello-be:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
